// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CityOverview.proto

package com.damuzhi.travel.protos;

public final class CityOverviewProtos {
  private CityOverviewProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommonOverviewOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string images = 1;
    java.util.List<String> getImagesList();
    int getImagesCount();
    String getImages(int index);
    
    // required string html = 2;
    boolean hasHtml();
    String getHtml();
  }
  public static final class CommonOverview extends
      com.google.protobuf.GeneratedMessage
      implements CommonOverviewOrBuilder {
    // Use CommonOverview.newBuilder() to construct.
    private CommonOverview(Builder builder) {
      super(builder);
    }
    private CommonOverview(boolean noInit) {}
    
    private static final CommonOverview defaultInstance;
    public static CommonOverview getDefaultInstance() {
      return defaultInstance;
    }
    
    public CommonOverview getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.CityOverviewProtos.internal_static_damuzhi_CommonOverview_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.damuzhi.travel.protos.CityOverviewProtos.internal_static_damuzhi_CommonOverview_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated string images = 1;
    public static final int IMAGES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList images_;
    public java.util.List<String>
        getImagesList() {
      return images_;
    }
    public int getImagesCount() {
      return images_.size();
    }
    public String getImages(int index) {
      return images_.get(index);
    }
    
    // required string html = 2;
    public static final int HTML_FIELD_NUMBER = 2;
    private java.lang.Object html_;
    public boolean hasHtml() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getHtml() {
      java.lang.Object ref = html_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          html_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHtmlBytes() {
      java.lang.Object ref = html_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        html_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      html_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHtml()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < images_.size(); i++) {
        output.writeBytes(1, images_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getHtmlBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < images_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(images_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getImagesList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHtmlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.damuzhi.travel.protos.CityOverviewProtos.internal_static_damuzhi_CommonOverview_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.damuzhi.travel.protos.CityOverviewProtos.internal_static_damuzhi_CommonOverview_fieldAccessorTable;
      }
      
      // Construct using com.lk.damuzhi.util.CityOverviewProtos.CommonOverview.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        html_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDescriptor();
      }
      
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getDefaultInstanceForType() {
        return com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      }
      
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview build() {
        com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview buildPartial() {
        com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview result = new com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          images_ = new com.google.protobuf.UnmodifiableLazyStringList(
              images_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.images_ = images_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.html_ = html_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview) {
          return mergeFrom((com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview other) {
        if (other == com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance()) return this;
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
        if (other.hasHtml()) {
          setHtml(other.getHtml());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHtml()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureImagesIsMutable();
              images_.add(input.readBytes());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              html_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string images = 1;
      private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          images_ = new com.google.protobuf.LazyStringArrayList(images_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getImagesList() {
        return java.util.Collections.unmodifiableList(images_);
      }
      public int getImagesCount() {
        return images_.size();
      }
      public String getImages(int index) {
        return images_.get(index);
      }
      public Builder setImages(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addImages(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllImages(
          java.lang.Iterable<String> values) {
        ensureImagesIsMutable();
        super.addAll(values, images_);
        onChanged();
        return this;
      }
      public Builder clearImages() {
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addImages(com.google.protobuf.ByteString value) {
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
      }
      
      // required string html = 2;
      private java.lang.Object html_ = "";
      public boolean hasHtml() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getHtml() {
        java.lang.Object ref = html_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          html_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHtml(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        html_ = value;
        onChanged();
        return this;
      }
      public Builder clearHtml() {
        bitField0_ = (bitField0_ & ~0x00000002);
        html_ = getDefaultInstance().getHtml();
        onChanged();
        return this;
      }
      void setHtml(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        html_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:damuzhi.CommonOverview)
    }
    
    static {
      defaultInstance = new CommonOverview(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:damuzhi.CommonOverview)
  }
  
  public interface CityOverviewOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .damuzhi.CommonOverview cityBasic = 1;
    boolean hasCityBasic();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getCityBasic();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getCityBasicOrBuilder();
    
    // optional .damuzhi.CommonOverview travelPrepration = 2;
    boolean hasTravelPrepration();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelPrepration();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelPreprationOrBuilder();
    
    // optional .damuzhi.CommonOverview travelUtility = 3;
    boolean hasTravelUtility();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelUtility();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelUtilityOrBuilder();
    
    // optional .damuzhi.CommonOverview travelTransportation = 4;
    boolean hasTravelTransportation();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelTransportation();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelTransportationOrBuilder();
  }
  public static final class CityOverview extends
      com.google.protobuf.GeneratedMessage
      implements CityOverviewOrBuilder {
    // Use CityOverview.newBuilder() to construct.
    private CityOverview(Builder builder) {
      super(builder);
    }
    private CityOverview(boolean noInit) {}
    
    private static final CityOverview defaultInstance;
    public static CityOverview getDefaultInstance() {
      return defaultInstance;
    }
    
    public CityOverview getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.CityOverviewProtos.internal_static_damuzhi_CityOverview_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.damuzhi.travel.protos.CityOverviewProtos.internal_static_damuzhi_CityOverview_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .damuzhi.CommonOverview cityBasic = 1;
    public static final int CITYBASIC_FIELD_NUMBER = 1;
    private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview cityBasic_;
    public boolean hasCityBasic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getCityBasic() {
      return cityBasic_;
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getCityBasicOrBuilder() {
      return cityBasic_;
    }
    
    // optional .damuzhi.CommonOverview travelPrepration = 2;
    public static final int TRAVELPREPRATION_FIELD_NUMBER = 2;
    private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview travelPrepration_;
    public boolean hasTravelPrepration() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelPrepration() {
      return travelPrepration_;
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelPreprationOrBuilder() {
      return travelPrepration_;
    }
    
    // optional .damuzhi.CommonOverview travelUtility = 3;
    public static final int TRAVELUTILITY_FIELD_NUMBER = 3;
    private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview travelUtility_;
    public boolean hasTravelUtility() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelUtility() {
      return travelUtility_;
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelUtilityOrBuilder() {
      return travelUtility_;
    }
    
    // optional .damuzhi.CommonOverview travelTransportation = 4;
    public static final int TRAVELTRANSPORTATION_FIELD_NUMBER = 4;
    private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview travelTransportation_;
    public boolean hasTravelTransportation() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelTransportation() {
      return travelTransportation_;
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelTransportationOrBuilder() {
      return travelTransportation_;
    }
    
    private void initFields() {
      cityBasic_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      travelPrepration_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      travelUtility_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      travelTransportation_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasCityBasic()) {
        if (!getCityBasic().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTravelPrepration()) {
        if (!getTravelPrepration().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTravelUtility()) {
        if (!getTravelUtility().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTravelTransportation()) {
        if (!getTravelTransportation().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, cityBasic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, travelPrepration_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, travelUtility_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, travelTransportation_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cityBasic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, travelPrepration_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, travelUtility_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, travelTransportation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.CityOverviewProtos.CityOverview parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.damuzhi.travel.protos.CityOverviewProtos.CityOverview prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.damuzhi.travel.protos.CityOverviewProtos.CityOverviewOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.damuzhi.travel.protos.CityOverviewProtos.internal_static_damuzhi_CityOverview_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.damuzhi.travel.protos.CityOverviewProtos.internal_static_damuzhi_CityOverview_fieldAccessorTable;
      }
      
      // Construct using com.lk.damuzhi.util.CityOverviewProtos.CityOverview.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCityBasicFieldBuilder();
          getTravelPreprationFieldBuilder();
          getTravelUtilityFieldBuilder();
          getTravelTransportationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (cityBasicBuilder_ == null) {
          cityBasic_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
        } else {
          cityBasicBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (travelPreprationBuilder_ == null) {
          travelPrepration_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
        } else {
          travelPreprationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (travelUtilityBuilder_ == null) {
          travelUtility_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
        } else {
          travelUtilityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (travelTransportationBuilder_ == null) {
          travelTransportation_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
        } else {
          travelTransportationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.damuzhi.travel.protos.CityOverviewProtos.CityOverview.getDescriptor();
      }
      
      public com.damuzhi.travel.protos.CityOverviewProtos.CityOverview getDefaultInstanceForType() {
        return com.damuzhi.travel.protos.CityOverviewProtos.CityOverview.getDefaultInstance();
      }
      
      public com.damuzhi.travel.protos.CityOverviewProtos.CityOverview build() {
        com.damuzhi.travel.protos.CityOverviewProtos.CityOverview result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.damuzhi.travel.protos.CityOverviewProtos.CityOverview buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.damuzhi.travel.protos.CityOverviewProtos.CityOverview result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.damuzhi.travel.protos.CityOverviewProtos.CityOverview buildPartial() {
        com.damuzhi.travel.protos.CityOverviewProtos.CityOverview result = new com.damuzhi.travel.protos.CityOverviewProtos.CityOverview(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (cityBasicBuilder_ == null) {
          result.cityBasic_ = cityBasic_;
        } else {
          result.cityBasic_ = cityBasicBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (travelPreprationBuilder_ == null) {
          result.travelPrepration_ = travelPrepration_;
        } else {
          result.travelPrepration_ = travelPreprationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (travelUtilityBuilder_ == null) {
          result.travelUtility_ = travelUtility_;
        } else {
          result.travelUtility_ = travelUtilityBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (travelTransportationBuilder_ == null) {
          result.travelTransportation_ = travelTransportation_;
        } else {
          result.travelTransportation_ = travelTransportationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.damuzhi.travel.protos.CityOverviewProtos.CityOverview) {
          return mergeFrom((com.damuzhi.travel.protos.CityOverviewProtos.CityOverview)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.damuzhi.travel.protos.CityOverviewProtos.CityOverview other) {
        if (other == com.damuzhi.travel.protos.CityOverviewProtos.CityOverview.getDefaultInstance()) return this;
        if (other.hasCityBasic()) {
          mergeCityBasic(other.getCityBasic());
        }
        if (other.hasTravelPrepration()) {
          mergeTravelPrepration(other.getTravelPrepration());
        }
        if (other.hasTravelUtility()) {
          mergeTravelUtility(other.getTravelUtility());
        }
        if (other.hasTravelTransportation()) {
          mergeTravelTransportation(other.getTravelTransportation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasCityBasic()) {
          if (!getCityBasic().isInitialized()) {
            
            return false;
          }
        }
        if (hasTravelPrepration()) {
          if (!getTravelPrepration().isInitialized()) {
            
            return false;
          }
        }
        if (hasTravelUtility()) {
          if (!getTravelUtility().isInitialized()) {
            
            return false;
          }
        }
        if (hasTravelTransportation()) {
          if (!getTravelTransportation().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder subBuilder = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder();
              if (hasCityBasic()) {
                subBuilder.mergeFrom(getCityBasic());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCityBasic(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder subBuilder = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder();
              if (hasTravelPrepration()) {
                subBuilder.mergeFrom(getTravelPrepration());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTravelPrepration(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder subBuilder = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder();
              if (hasTravelUtility()) {
                subBuilder.mergeFrom(getTravelUtility());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTravelUtility(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder subBuilder = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder();
              if (hasTravelTransportation()) {
                subBuilder.mergeFrom(getTravelTransportation());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTravelTransportation(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .damuzhi.CommonOverview cityBasic = 1;
      private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview cityBasic_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> cityBasicBuilder_;
      public boolean hasCityBasic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getCityBasic() {
        if (cityBasicBuilder_ == null) {
          return cityBasic_;
        } else {
          return cityBasicBuilder_.getMessage();
        }
      }
      public Builder setCityBasic(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (cityBasicBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cityBasic_ = value;
          onChanged();
        } else {
          cityBasicBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setCityBasic(
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder builderForValue) {
        if (cityBasicBuilder_ == null) {
          cityBasic_ = builderForValue.build();
          onChanged();
        } else {
          cityBasicBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeCityBasic(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (cityBasicBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              cityBasic_ != com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance()) {
            cityBasic_ =
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder(cityBasic_).mergeFrom(value).buildPartial();
          } else {
            cityBasic_ = value;
          }
          onChanged();
        } else {
          cityBasicBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearCityBasic() {
        if (cityBasicBuilder_ == null) {
          cityBasic_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
          onChanged();
        } else {
          cityBasicBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder getCityBasicBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCityBasicFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getCityBasicOrBuilder() {
        if (cityBasicBuilder_ != null) {
          return cityBasicBuilder_.getMessageOrBuilder();
        } else {
          return cityBasic_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> 
          getCityBasicFieldBuilder() {
        if (cityBasicBuilder_ == null) {
          cityBasicBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder>(
                  cityBasic_,
                  getParentForChildren(),
                  isClean());
          cityBasic_ = null;
        }
        return cityBasicBuilder_;
      }
      
      // optional .damuzhi.CommonOverview travelPrepration = 2;
      private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview travelPrepration_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> travelPreprationBuilder_;
      public boolean hasTravelPrepration() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelPrepration() {
        if (travelPreprationBuilder_ == null) {
          return travelPrepration_;
        } else {
          return travelPreprationBuilder_.getMessage();
        }
      }
      public Builder setTravelPrepration(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (travelPreprationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          travelPrepration_ = value;
          onChanged();
        } else {
          travelPreprationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setTravelPrepration(
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder builderForValue) {
        if (travelPreprationBuilder_ == null) {
          travelPrepration_ = builderForValue.build();
          onChanged();
        } else {
          travelPreprationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeTravelPrepration(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (travelPreprationBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              travelPrepration_ != com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance()) {
            travelPrepration_ =
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder(travelPrepration_).mergeFrom(value).buildPartial();
          } else {
            travelPrepration_ = value;
          }
          onChanged();
        } else {
          travelPreprationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearTravelPrepration() {
        if (travelPreprationBuilder_ == null) {
          travelPrepration_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
          onChanged();
        } else {
          travelPreprationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder getTravelPreprationBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTravelPreprationFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelPreprationOrBuilder() {
        if (travelPreprationBuilder_ != null) {
          return travelPreprationBuilder_.getMessageOrBuilder();
        } else {
          return travelPrepration_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> 
          getTravelPreprationFieldBuilder() {
        if (travelPreprationBuilder_ == null) {
          travelPreprationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder>(
                  travelPrepration_,
                  getParentForChildren(),
                  isClean());
          travelPrepration_ = null;
        }
        return travelPreprationBuilder_;
      }
      
      // optional .damuzhi.CommonOverview travelUtility = 3;
      private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview travelUtility_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> travelUtilityBuilder_;
      public boolean hasTravelUtility() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelUtility() {
        if (travelUtilityBuilder_ == null) {
          return travelUtility_;
        } else {
          return travelUtilityBuilder_.getMessage();
        }
      }
      public Builder setTravelUtility(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (travelUtilityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          travelUtility_ = value;
          onChanged();
        } else {
          travelUtilityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setTravelUtility(
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder builderForValue) {
        if (travelUtilityBuilder_ == null) {
          travelUtility_ = builderForValue.build();
          onChanged();
        } else {
          travelUtilityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeTravelUtility(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (travelUtilityBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              travelUtility_ != com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance()) {
            travelUtility_ =
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder(travelUtility_).mergeFrom(value).buildPartial();
          } else {
            travelUtility_ = value;
          }
          onChanged();
        } else {
          travelUtilityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearTravelUtility() {
        if (travelUtilityBuilder_ == null) {
          travelUtility_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
          onChanged();
        } else {
          travelUtilityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder getTravelUtilityBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTravelUtilityFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelUtilityOrBuilder() {
        if (travelUtilityBuilder_ != null) {
          return travelUtilityBuilder_.getMessageOrBuilder();
        } else {
          return travelUtility_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> 
          getTravelUtilityFieldBuilder() {
        if (travelUtilityBuilder_ == null) {
          travelUtilityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder>(
                  travelUtility_,
                  getParentForChildren(),
                  isClean());
          travelUtility_ = null;
        }
        return travelUtilityBuilder_;
      }
      
      // optional .damuzhi.CommonOverview travelTransportation = 4;
      private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview travelTransportation_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> travelTransportationBuilder_;
      public boolean hasTravelTransportation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getTravelTransportation() {
        if (travelTransportationBuilder_ == null) {
          return travelTransportation_;
        } else {
          return travelTransportationBuilder_.getMessage();
        }
      }
      public Builder setTravelTransportation(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (travelTransportationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          travelTransportation_ = value;
          onChanged();
        } else {
          travelTransportationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setTravelTransportation(
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder builderForValue) {
        if (travelTransportationBuilder_ == null) {
          travelTransportation_ = builderForValue.build();
          onChanged();
        } else {
          travelTransportationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeTravelTransportation(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (travelTransportationBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              travelTransportation_ != com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance()) {
            travelTransportation_ =
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder(travelTransportation_).mergeFrom(value).buildPartial();
          } else {
            travelTransportation_ = value;
          }
          onChanged();
        } else {
          travelTransportationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearTravelTransportation() {
        if (travelTransportationBuilder_ == null) {
          travelTransportation_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
          onChanged();
        } else {
          travelTransportationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder getTravelTransportationBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTravelTransportationFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getTravelTransportationOrBuilder() {
        if (travelTransportationBuilder_ != null) {
          return travelTransportationBuilder_.getMessageOrBuilder();
        } else {
          return travelTransportation_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> 
          getTravelTransportationFieldBuilder() {
        if (travelTransportationBuilder_ == null) {
          travelTransportationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder>(
                  travelTransportation_,
                  getParentForChildren(),
                  isClean());
          travelTransportation_ = null;
        }
        return travelTransportationBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:damuzhi.CityOverview)
    }
    
    static {
      defaultInstance = new CityOverview(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:damuzhi.CityOverview)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_damuzhi_CommonOverview_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_damuzhi_CommonOverview_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_damuzhi_CityOverview_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_damuzhi_CityOverview_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CityOverview.proto\022\007damuzhi\".\n\016CommonO" +
      "verview\022\016\n\006images\030\001 \003(\t\022\014\n\004html\030\002 \002(\t\"\324\001" +
      "\n\014CityOverview\022*\n\tcityBasic\030\001 \001(\0132\027.damu" +
      "zhi.CommonOverview\0221\n\020travelPrepration\030\002" +
      " \001(\0132\027.damuzhi.CommonOverview\022.\n\rtravelU" +
      "tility\030\003 \001(\0132\027.damuzhi.CommonOverview\0225\n" +
      "\024travelTransportation\030\004 \001(\0132\027.damuzhi.Co" +
      "mmonOverviewB)\n\023com.lk.damuzhi.utilB\022Cit" +
      "yOverviewProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_damuzhi_CommonOverview_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_damuzhi_CommonOverview_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_damuzhi_CommonOverview_descriptor,
              new java.lang.String[] { "Images", "Html", },
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.class,
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder.class);
          internal_static_damuzhi_CityOverview_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_damuzhi_CityOverview_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_damuzhi_CityOverview_descriptor,
              new java.lang.String[] { "CityBasic", "TravelPrepration", "TravelUtility", "TravelTransportation", },
              com.damuzhi.travel.protos.CityOverviewProtos.CityOverview.class,
              com.damuzhi.travel.protos.CityOverviewProtos.CityOverview.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
