// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Package.proto

package com.damuzhi.travel.protos;

public final class PackageProtos {
  private PackageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum LanguageType
      implements com.google.protobuf.ProtocolMessageEnum {
    ZH_HANS(0, 1),
    ZH_HANT(1, 2),
    EN(2, 3),
    ;
    
    public static final int ZH_HANS_VALUE = 1;
    public static final int ZH_HANT_VALUE = 2;
    public static final int EN_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static LanguageType valueOf(int value) {
      switch (value) {
        case 1: return ZH_HANS;
        case 2: return ZH_HANT;
        case 3: return EN;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<LanguageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LanguageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LanguageType>() {
            public LanguageType findValueByNumber(int number) {
              return LanguageType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.PackageProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final LanguageType[] VALUES = {
      ZH_HANS, ZH_HANT, EN, 
    };
    
    public static LanguageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private LanguageType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:damuzhi.LanguageType)
  }
  
  public interface PackageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string version = 1;
    boolean hasVersion();
    String getVersion();
    
    // required int32 cityId = 2;
    boolean hasCityId();
    int getCityId();
    
    // required string cityName = 3;
    boolean hasCityName();
    String getCityName();
    
    // required .damuzhi.LanguageType language = 4 [default = ZH_HANS];
    boolean hasLanguage();
    com.damuzhi.travel.protos.PackageProtos.LanguageType getLanguage();
  }
  public static final class Package extends
      com.google.protobuf.GeneratedMessage
      implements PackageOrBuilder {
    // Use Package.newBuilder() to construct.
    private Package(Builder builder) {
      super(builder);
    }
    private Package(boolean noInit) {}
    
    private static final Package defaultInstance;
    public static Package getDefaultInstance() {
      return defaultInstance;
    }
    
    public Package getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.PackageProtos.internal_static_damuzhi_Package_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.damuzhi.travel.protos.PackageProtos.internal_static_damuzhi_Package_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private java.lang.Object version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          version_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 cityId = 2;
    public static final int CITYID_FIELD_NUMBER = 2;
    private int cityId_;
    public boolean hasCityId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCityId() {
      return cityId_;
    }
    
    // required string cityName = 3;
    public static final int CITYNAME_FIELD_NUMBER = 3;
    private java.lang.Object cityName_;
    public boolean hasCityName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getCityName() {
      java.lang.Object ref = cityName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cityName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCityNameBytes() {
      java.lang.Object ref = cityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .damuzhi.LanguageType language = 4 [default = ZH_HANS];
    public static final int LANGUAGE_FIELD_NUMBER = 4;
    private com.damuzhi.travel.protos.PackageProtos.LanguageType language_;
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.damuzhi.travel.protos.PackageProtos.LanguageType getLanguage() {
      return language_;
    }
    
    private void initFields() {
      version_ = "";
      cityId_ = 0;
      cityName_ = "";
      language_ = com.damuzhi.travel.protos.PackageProtos.LanguageType.ZH_HANS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCityId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCityName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLanguage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cityId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCityNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, language_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cityId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCityNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, language_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.damuzhi.travel.protos.PackageProtos.Package parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.Package parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.damuzhi.travel.protos.PackageProtos.Package prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.damuzhi.travel.protos.PackageProtos.PackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.damuzhi.travel.protos.PackageProtos.internal_static_damuzhi_Package_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.damuzhi.travel.protos.PackageProtos.internal_static_damuzhi_Package_fieldAccessorTable;
      }
      
      // Construct using com.lk.damuzhi.util.PackageProtos.Package.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cityId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        cityName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        language_ = com.damuzhi.travel.protos.PackageProtos.LanguageType.ZH_HANS;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.damuzhi.travel.protos.PackageProtos.Package.getDescriptor();
      }
      
      public com.damuzhi.travel.protos.PackageProtos.Package getDefaultInstanceForType() {
        return com.damuzhi.travel.protos.PackageProtos.Package.getDefaultInstance();
      }
      
      public com.damuzhi.travel.protos.PackageProtos.Package build() {
        com.damuzhi.travel.protos.PackageProtos.Package result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.damuzhi.travel.protos.PackageProtos.Package buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.damuzhi.travel.protos.PackageProtos.Package result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.damuzhi.travel.protos.PackageProtos.Package buildPartial() {
        com.damuzhi.travel.protos.PackageProtos.Package result = new com.damuzhi.travel.protos.PackageProtos.Package(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cityId_ = cityId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cityName_ = cityName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.language_ = language_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.damuzhi.travel.protos.PackageProtos.Package) {
          return mergeFrom((com.damuzhi.travel.protos.PackageProtos.Package)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.damuzhi.travel.protos.PackageProtos.Package other) {
        if (other == com.damuzhi.travel.protos.PackageProtos.Package.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasCityId()) {
          setCityId(other.getCityId());
        }
        if (other.hasCityName()) {
          setCityName(other.getCityName());
        }
        if (other.hasLanguage()) {
          setLanguage(other.getLanguage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasCityId()) {
          
          return false;
        }
        if (!hasCityName()) {
          
          return false;
        }
        if (!hasLanguage()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              version_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cityId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              cityName_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.damuzhi.travel.protos.PackageProtos.LanguageType value = com.damuzhi.travel.protos.PackageProtos.LanguageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                language_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string version = 1;
      private java.lang.Object version_ = "";
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      void setVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
      }
      
      // required int32 cityId = 2;
      private int cityId_ ;
      public boolean hasCityId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCityId() {
        return cityId_;
      }
      public Builder setCityId(int value) {
        bitField0_ |= 0x00000002;
        cityId_ = value;
        onChanged();
        return this;
      }
      public Builder clearCityId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cityId_ = 0;
        onChanged();
        return this;
      }
      
      // required string cityName = 3;
      private java.lang.Object cityName_ = "";
      public boolean hasCityName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getCityName() {
        java.lang.Object ref = cityName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cityName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCityName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cityName_ = value;
        onChanged();
        return this;
      }
      public Builder clearCityName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cityName_ = getDefaultInstance().getCityName();
        onChanged();
        return this;
      }
      void setCityName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        cityName_ = value;
        onChanged();
      }
      
      // required .damuzhi.LanguageType language = 4 [default = ZH_HANS];
      private com.damuzhi.travel.protos.PackageProtos.LanguageType language_ = com.damuzhi.travel.protos.PackageProtos.LanguageType.ZH_HANS;
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.damuzhi.travel.protos.PackageProtos.LanguageType getLanguage() {
        return language_;
      }
      public Builder setLanguage(com.damuzhi.travel.protos.PackageProtos.LanguageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        language_ = value;
        onChanged();
        return this;
      }
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        language_ = com.damuzhi.travel.protos.PackageProtos.LanguageType.ZH_HANS;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:damuzhi.Package)
    }
    
    static {
      defaultInstance = new Package(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:damuzhi.Package)
  }
  
  public interface TravelResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 resultCode = 1 [default = 0];
    boolean hasResultCode();
    int getResultCode();
    
    // optional string resultInfo = 2;
    boolean hasResultInfo();
    String getResultInfo();
    
    // optional .damuzhi.Place place = 3;
    boolean hasPlace();
    com.damuzhi.travel.protos.PlaceListProtos.Place getPlace();
    com.damuzhi.travel.protos.PlaceListProtos.PlaceOrBuilder getPlaceOrBuilder();
    
    // optional .damuzhi.CommonOverview overview = 4;
    boolean hasOverview();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getOverview();
    com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getOverviewOrBuilder();
    
    // optional .damuzhi.CommonTravelTip travelTip = 5;
    boolean hasTravelTip();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getTravelTip();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getTravelTipOrBuilder();
    
    // optional .damuzhi.HelpInfo helpInfo = 6;
    boolean hasHelpInfo();
    com.damuzhi.travel.protos.AppProtos.HelpInfo getHelpInfo();
    com.damuzhi.travel.protos.AppProtos.HelpInfoOrBuilder getHelpInfoOrBuilder();
    
    // optional .damuzhi.PlaceList placeList = 7;
    boolean hasPlaceList();
    com.damuzhi.travel.protos.PlaceListProtos.PlaceList getPlaceList();
    com.damuzhi.travel.protos.PlaceListProtos.PlaceListOrBuilder getPlaceListOrBuilder();
    
    // optional .damuzhi.CityList cityList = 8;
    boolean hasCityList();
    com.damuzhi.travel.protos.AppProtos.CityList getCityList();
    com.damuzhi.travel.protos.AppProtos.CityListOrBuilder getCityListOrBuilder();
    
    // optional .damuzhi.App appInfo = 9;
    boolean hasAppInfo();
    com.damuzhi.travel.protos.AppProtos.App getAppInfo();
    com.damuzhi.travel.protos.AppProtos.AppOrBuilder getAppInfoOrBuilder();
    
    // optional .damuzhi.CommonTravelTipList travelTipList = 10;
    boolean hasTravelTipList();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList getTravelTipList();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipListOrBuilder getTravelTipListOrBuilder();
  }
  public static final class TravelResponse extends
      com.google.protobuf.GeneratedMessage
      implements TravelResponseOrBuilder {
    // Use TravelResponse.newBuilder() to construct.
    private TravelResponse(Builder builder) {
      super(builder);
    }
    private TravelResponse(boolean noInit) {}
    
    private static final TravelResponse defaultInstance;
    public static TravelResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public TravelResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.PackageProtos.internal_static_damuzhi_TravelResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.damuzhi.travel.protos.PackageProtos.internal_static_damuzhi_TravelResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 resultCode = 1 [default = 0];
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private int resultCode_;
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResultCode() {
      return resultCode_;
    }
    
    // optional string resultInfo = 2;
    public static final int RESULTINFO_FIELD_NUMBER = 2;
    private java.lang.Object resultInfo_;
    public boolean hasResultInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getResultInfo() {
      java.lang.Object ref = resultInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          resultInfo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResultInfoBytes() {
      java.lang.Object ref = resultInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        resultInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .damuzhi.Place place = 3;
    public static final int PLACE_FIELD_NUMBER = 3;
    private com.damuzhi.travel.protos.PlaceListProtos.Place place_;
    public boolean hasPlace() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.damuzhi.travel.protos.PlaceListProtos.Place getPlace() {
      return place_;
    }
    public com.damuzhi.travel.protos.PlaceListProtos.PlaceOrBuilder getPlaceOrBuilder() {
      return place_;
    }
    
    // optional .damuzhi.CommonOverview overview = 4;
    public static final int OVERVIEW_FIELD_NUMBER = 4;
    private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview overview_;
    public boolean hasOverview() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getOverview() {
      return overview_;
    }
    public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getOverviewOrBuilder() {
      return overview_;
    }
    
    // optional .damuzhi.CommonTravelTip travelTip = 5;
    public static final int TRAVELTIP_FIELD_NUMBER = 5;
    private com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip travelTip_;
    public boolean hasTravelTip() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getTravelTip() {
      return travelTip_;
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getTravelTipOrBuilder() {
      return travelTip_;
    }
    
    // optional .damuzhi.HelpInfo helpInfo = 6;
    public static final int HELPINFO_FIELD_NUMBER = 6;
    private com.damuzhi.travel.protos.AppProtos.HelpInfo helpInfo_;
    public boolean hasHelpInfo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.damuzhi.travel.protos.AppProtos.HelpInfo getHelpInfo() {
      return helpInfo_;
    }
    public com.damuzhi.travel.protos.AppProtos.HelpInfoOrBuilder getHelpInfoOrBuilder() {
      return helpInfo_;
    }
    
    // optional .damuzhi.PlaceList placeList = 7;
    public static final int PLACELIST_FIELD_NUMBER = 7;
    private com.damuzhi.travel.protos.PlaceListProtos.PlaceList placeList_;
    public boolean hasPlaceList() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.damuzhi.travel.protos.PlaceListProtos.PlaceList getPlaceList() {
      return placeList_;
    }
    public com.damuzhi.travel.protos.PlaceListProtos.PlaceListOrBuilder getPlaceListOrBuilder() {
      return placeList_;
    }
    
    // optional .damuzhi.CityList cityList = 8;
    public static final int CITYLIST_FIELD_NUMBER = 8;
    private com.damuzhi.travel.protos.AppProtos.CityList cityList_;
    public boolean hasCityList() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.damuzhi.travel.protos.AppProtos.CityList getCityList() {
      return cityList_;
    }
    public com.damuzhi.travel.protos.AppProtos.CityListOrBuilder getCityListOrBuilder() {
      return cityList_;
    }
    
    // optional .damuzhi.App appInfo = 9;
    public static final int APPINFO_FIELD_NUMBER = 9;
    private com.damuzhi.travel.protos.AppProtos.App appInfo_;
    public boolean hasAppInfo() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public com.damuzhi.travel.protos.AppProtos.App getAppInfo() {
      return appInfo_;
    }
    public com.damuzhi.travel.protos.AppProtos.AppOrBuilder getAppInfoOrBuilder() {
      return appInfo_;
    }
    
    // optional .damuzhi.CommonTravelTipList travelTipList = 10;
    public static final int TRAVELTIPLIST_FIELD_NUMBER = 10;
    private com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList travelTipList_;
    public boolean hasTravelTipList() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList getTravelTipList() {
      return travelTipList_;
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipListOrBuilder getTravelTipListOrBuilder() {
      return travelTipList_;
    }
    
    private void initFields() {
      resultCode_ = 0;
      resultInfo_ = "";
      place_ = com.damuzhi.travel.protos.PlaceListProtos.Place.getDefaultInstance();
      overview_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      travelTip_ = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance();
      helpInfo_ = com.damuzhi.travel.protos.AppProtos.HelpInfo.getDefaultInstance();
      placeList_ = com.damuzhi.travel.protos.PlaceListProtos.PlaceList.getDefaultInstance();
      cityList_ = com.damuzhi.travel.protos.AppProtos.CityList.getDefaultInstance();
      appInfo_ = com.damuzhi.travel.protos.AppProtos.App.getDefaultInstance();
      travelTipList_ = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPlace()) {
        if (!getPlace().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasOverview()) {
        if (!getOverview().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTravelTip()) {
        if (!getTravelTip().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPlaceList()) {
        if (!getPlaceList().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasCityList()) {
        if (!getCityList().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAppInfo()) {
        if (!getAppInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTravelTipList()) {
        if (!getTravelTipList().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResultInfoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, place_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, overview_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, travelTip_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, helpInfo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, placeList_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, cityList_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, appInfo_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, travelTipList_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResultInfoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, place_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, overview_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, travelTip_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, helpInfo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, placeList_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, cityList_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, appInfo_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, travelTipList_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.PackageProtos.TravelResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.damuzhi.travel.protos.PackageProtos.TravelResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.damuzhi.travel.protos.PackageProtos.TravelResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.damuzhi.travel.protos.PackageProtos.internal_static_damuzhi_TravelResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.damuzhi.travel.protos.PackageProtos.internal_static_damuzhi_TravelResponse_fieldAccessorTable;
      }
      
      // Construct using com.lk.damuzhi.util.PackageProtos.TravelResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlaceFieldBuilder();
          getOverviewFieldBuilder();
          getTravelTipFieldBuilder();
          getHelpInfoFieldBuilder();
          getPlaceListFieldBuilder();
          getCityListFieldBuilder();
          getAppInfoFieldBuilder();
          getTravelTipListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (placeBuilder_ == null) {
          place_ = com.damuzhi.travel.protos.PlaceListProtos.Place.getDefaultInstance();
        } else {
          placeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (overviewBuilder_ == null) {
          overview_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
        } else {
          overviewBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (travelTipBuilder_ == null) {
          travelTip_ = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance();
        } else {
          travelTipBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (helpInfoBuilder_ == null) {
          helpInfo_ = com.damuzhi.travel.protos.AppProtos.HelpInfo.getDefaultInstance();
        } else {
          helpInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (placeListBuilder_ == null) {
          placeList_ = com.damuzhi.travel.protos.PlaceListProtos.PlaceList.getDefaultInstance();
        } else {
          placeListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (cityListBuilder_ == null) {
          cityList_ = com.damuzhi.travel.protos.AppProtos.CityList.getDefaultInstance();
        } else {
          cityListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        if (appInfoBuilder_ == null) {
          appInfo_ = com.damuzhi.travel.protos.AppProtos.App.getDefaultInstance();
        } else {
          appInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        if (travelTipListBuilder_ == null) {
          travelTipList_ = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.getDefaultInstance();
        } else {
          travelTipListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.damuzhi.travel.protos.PackageProtos.TravelResponse.getDescriptor();
      }
      
      public com.damuzhi.travel.protos.PackageProtos.TravelResponse getDefaultInstanceForType() {
        return com.damuzhi.travel.protos.PackageProtos.TravelResponse.getDefaultInstance();
      }
      
      public com.damuzhi.travel.protos.PackageProtos.TravelResponse build() {
        com.damuzhi.travel.protos.PackageProtos.TravelResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.damuzhi.travel.protos.PackageProtos.TravelResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.damuzhi.travel.protos.PackageProtos.TravelResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.damuzhi.travel.protos.PackageProtos.TravelResponse buildPartial() {
        com.damuzhi.travel.protos.PackageProtos.TravelResponse result = new com.damuzhi.travel.protos.PackageProtos.TravelResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultInfo_ = resultInfo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (placeBuilder_ == null) {
          result.place_ = place_;
        } else {
          result.place_ = placeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (overviewBuilder_ == null) {
          result.overview_ = overview_;
        } else {
          result.overview_ = overviewBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (travelTipBuilder_ == null) {
          result.travelTip_ = travelTip_;
        } else {
          result.travelTip_ = travelTipBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (helpInfoBuilder_ == null) {
          result.helpInfo_ = helpInfo_;
        } else {
          result.helpInfo_ = helpInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (placeListBuilder_ == null) {
          result.placeList_ = placeList_;
        } else {
          result.placeList_ = placeListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (cityListBuilder_ == null) {
          result.cityList_ = cityList_;
        } else {
          result.cityList_ = cityListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (appInfoBuilder_ == null) {
          result.appInfo_ = appInfo_;
        } else {
          result.appInfo_ = appInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (travelTipListBuilder_ == null) {
          result.travelTipList_ = travelTipList_;
        } else {
          result.travelTipList_ = travelTipListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.damuzhi.travel.protos.PackageProtos.TravelResponse) {
          return mergeFrom((com.damuzhi.travel.protos.PackageProtos.TravelResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.damuzhi.travel.protos.PackageProtos.TravelResponse other) {
        if (other == com.damuzhi.travel.protos.PackageProtos.TravelResponse.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasResultInfo()) {
          setResultInfo(other.getResultInfo());
        }
        if (other.hasPlace()) {
          mergePlace(other.getPlace());
        }
        if (other.hasOverview()) {
          mergeOverview(other.getOverview());
        }
        if (other.hasTravelTip()) {
          mergeTravelTip(other.getTravelTip());
        }
        if (other.hasHelpInfo()) {
          mergeHelpInfo(other.getHelpInfo());
        }
        if (other.hasPlaceList()) {
          mergePlaceList(other.getPlaceList());
        }
        if (other.hasCityList()) {
          mergeCityList(other.getCityList());
        }
        if (other.hasAppInfo()) {
          mergeAppInfo(other.getAppInfo());
        }
        if (other.hasTravelTipList()) {
          mergeTravelTipList(other.getTravelTipList());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        if (hasPlace()) {
          if (!getPlace().isInitialized()) {
            
            return false;
          }
        }
        if (hasOverview()) {
          if (!getOverview().isInitialized()) {
            
            return false;
          }
        }
        if (hasTravelTip()) {
          if (!getTravelTip().isInitialized()) {
            
            return false;
          }
        }
        if (hasPlaceList()) {
          if (!getPlaceList().isInitialized()) {
            
            return false;
          }
        }
        if (hasCityList()) {
          if (!getCityList().isInitialized()) {
            
            return false;
          }
        }
        if (hasAppInfo()) {
          if (!getAppInfo().isInitialized()) {
            
            return false;
          }
        }
        if (hasTravelTipList()) {
          if (!getTravelTipList().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultCode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              resultInfo_ = input.readBytes();
              break;
            }
            case 26: {
              com.damuzhi.travel.protos.PlaceListProtos.Place.Builder subBuilder = com.damuzhi.travel.protos.PlaceListProtos.Place.newBuilder();
              if (hasPlace()) {
                subBuilder.mergeFrom(getPlace());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPlace(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder subBuilder = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder();
              if (hasOverview()) {
                subBuilder.mergeFrom(getOverview());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOverview(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder subBuilder = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.newBuilder();
              if (hasTravelTip()) {
                subBuilder.mergeFrom(getTravelTip());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTravelTip(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.damuzhi.travel.protos.AppProtos.HelpInfo.Builder subBuilder = com.damuzhi.travel.protos.AppProtos.HelpInfo.newBuilder();
              if (hasHelpInfo()) {
                subBuilder.mergeFrom(getHelpInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHelpInfo(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.damuzhi.travel.protos.PlaceListProtos.PlaceList.Builder subBuilder = com.damuzhi.travel.protos.PlaceListProtos.PlaceList.newBuilder();
              if (hasPlaceList()) {
                subBuilder.mergeFrom(getPlaceList());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPlaceList(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.damuzhi.travel.protos.AppProtos.CityList.Builder subBuilder = com.damuzhi.travel.protos.AppProtos.CityList.newBuilder();
              if (hasCityList()) {
                subBuilder.mergeFrom(getCityList());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCityList(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.damuzhi.travel.protos.AppProtos.App.Builder subBuilder = com.damuzhi.travel.protos.AppProtos.App.newBuilder();
              if (hasAppInfo()) {
                subBuilder.mergeFrom(getAppInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAppInfo(subBuilder.buildPartial());
              break;
            }
            case 82: {
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.Builder subBuilder = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.newBuilder();
              if (hasTravelTipList()) {
                subBuilder.mergeFrom(getTravelTipList());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTravelTipList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 resultCode = 1 [default = 0];
      private int resultCode_ ;
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResultCode() {
        return resultCode_;
      }
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string resultInfo = 2;
      private java.lang.Object resultInfo_ = "";
      public boolean hasResultInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getResultInfo() {
        java.lang.Object ref = resultInfo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          resultInfo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResultInfo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultInfo_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultInfo_ = getDefaultInstance().getResultInfo();
        onChanged();
        return this;
      }
      void setResultInfo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        resultInfo_ = value;
        onChanged();
      }
      
      // optional .damuzhi.Place place = 3;
      private com.damuzhi.travel.protos.PlaceListProtos.Place place_ = com.damuzhi.travel.protos.PlaceListProtos.Place.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.PlaceListProtos.Place, com.damuzhi.travel.protos.PlaceListProtos.Place.Builder, com.damuzhi.travel.protos.PlaceListProtos.PlaceOrBuilder> placeBuilder_;
      public boolean hasPlace() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.damuzhi.travel.protos.PlaceListProtos.Place getPlace() {
        if (placeBuilder_ == null) {
          return place_;
        } else {
          return placeBuilder_.getMessage();
        }
      }
      public Builder setPlace(com.damuzhi.travel.protos.PlaceListProtos.Place value) {
        if (placeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          place_ = value;
          onChanged();
        } else {
          placeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setPlace(
          com.damuzhi.travel.protos.PlaceListProtos.Place.Builder builderForValue) {
        if (placeBuilder_ == null) {
          place_ = builderForValue.build();
          onChanged();
        } else {
          placeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergePlace(com.damuzhi.travel.protos.PlaceListProtos.Place value) {
        if (placeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              place_ != com.damuzhi.travel.protos.PlaceListProtos.Place.getDefaultInstance()) {
            place_ =
              com.damuzhi.travel.protos.PlaceListProtos.Place.newBuilder(place_).mergeFrom(value).buildPartial();
          } else {
            place_ = value;
          }
          onChanged();
        } else {
          placeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearPlace() {
        if (placeBuilder_ == null) {
          place_ = com.damuzhi.travel.protos.PlaceListProtos.Place.getDefaultInstance();
          onChanged();
        } else {
          placeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.damuzhi.travel.protos.PlaceListProtos.Place.Builder getPlaceBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPlaceFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.PlaceListProtos.PlaceOrBuilder getPlaceOrBuilder() {
        if (placeBuilder_ != null) {
          return placeBuilder_.getMessageOrBuilder();
        } else {
          return place_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.PlaceListProtos.Place, com.damuzhi.travel.protos.PlaceListProtos.Place.Builder, com.damuzhi.travel.protos.PlaceListProtos.PlaceOrBuilder> 
          getPlaceFieldBuilder() {
        if (placeBuilder_ == null) {
          placeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.PlaceListProtos.Place, com.damuzhi.travel.protos.PlaceListProtos.Place.Builder, com.damuzhi.travel.protos.PlaceListProtos.PlaceOrBuilder>(
                  place_,
                  getParentForChildren(),
                  isClean());
          place_ = null;
        }
        return placeBuilder_;
      }
      
      // optional .damuzhi.CommonOverview overview = 4;
      private com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview overview_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> overviewBuilder_;
      public boolean hasOverview() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview getOverview() {
        if (overviewBuilder_ == null) {
          return overview_;
        } else {
          return overviewBuilder_.getMessage();
        }
      }
      public Builder setOverview(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (overviewBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          overview_ = value;
          onChanged();
        } else {
          overviewBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setOverview(
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder builderForValue) {
        if (overviewBuilder_ == null) {
          overview_ = builderForValue.build();
          onChanged();
        } else {
          overviewBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeOverview(com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview value) {
        if (overviewBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              overview_ != com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance()) {
            overview_ =
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.newBuilder(overview_).mergeFrom(value).buildPartial();
          } else {
            overview_ = value;
          }
          onChanged();
        } else {
          overviewBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearOverview() {
        if (overviewBuilder_ == null) {
          overview_ = com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.getDefaultInstance();
          onChanged();
        } else {
          overviewBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder getOverviewBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getOverviewFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder getOverviewOrBuilder() {
        if (overviewBuilder_ != null) {
          return overviewBuilder_.getMessageOrBuilder();
        } else {
          return overview_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder> 
          getOverviewFieldBuilder() {
        if (overviewBuilder_ == null) {
          overviewBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverview.Builder, com.damuzhi.travel.protos.CityOverviewProtos.CommonOverviewOrBuilder>(
                  overview_,
                  getParentForChildren(),
                  isClean());
          overview_ = null;
        }
        return overviewBuilder_;
      }
      
      // optional .damuzhi.CommonTravelTip travelTip = 5;
      private com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip travelTip_ = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> travelTipBuilder_;
      public boolean hasTravelTip() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getTravelTip() {
        if (travelTipBuilder_ == null) {
          return travelTip_;
        } else {
          return travelTipBuilder_.getMessage();
        }
      }
      public Builder setTravelTip(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (travelTipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          travelTip_ = value;
          onChanged();
        } else {
          travelTipBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setTravelTip(
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (travelTipBuilder_ == null) {
          travelTip_ = builderForValue.build();
          onChanged();
        } else {
          travelTipBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeTravelTip(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (travelTipBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              travelTip_ != com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance()) {
            travelTip_ =
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.newBuilder(travelTip_).mergeFrom(value).buildPartial();
          } else {
            travelTip_ = value;
          }
          onChanged();
        } else {
          travelTipBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearTravelTip() {
        if (travelTipBuilder_ == null) {
          travelTip_ = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance();
          onChanged();
        } else {
          travelTipBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder getTravelTipBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getTravelTipFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getTravelTipOrBuilder() {
        if (travelTipBuilder_ != null) {
          return travelTipBuilder_.getMessageOrBuilder();
        } else {
          return travelTip_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
          getTravelTipFieldBuilder() {
        if (travelTipBuilder_ == null) {
          travelTipBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder>(
                  travelTip_,
                  getParentForChildren(),
                  isClean());
          travelTip_ = null;
        }
        return travelTipBuilder_;
      }
      
      // optional .damuzhi.HelpInfo helpInfo = 6;
      private com.damuzhi.travel.protos.AppProtos.HelpInfo helpInfo_ = com.damuzhi.travel.protos.AppProtos.HelpInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.AppProtos.HelpInfo, com.damuzhi.travel.protos.AppProtos.HelpInfo.Builder, com.damuzhi.travel.protos.AppProtos.HelpInfoOrBuilder> helpInfoBuilder_;
      public boolean hasHelpInfo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.damuzhi.travel.protos.AppProtos.HelpInfo getHelpInfo() {
        if (helpInfoBuilder_ == null) {
          return helpInfo_;
        } else {
          return helpInfoBuilder_.getMessage();
        }
      }
      public Builder setHelpInfo(com.damuzhi.travel.protos.AppProtos.HelpInfo value) {
        if (helpInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          helpInfo_ = value;
          onChanged();
        } else {
          helpInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder setHelpInfo(
          com.damuzhi.travel.protos.AppProtos.HelpInfo.Builder builderForValue) {
        if (helpInfoBuilder_ == null) {
          helpInfo_ = builderForValue.build();
          onChanged();
        } else {
          helpInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder mergeHelpInfo(com.damuzhi.travel.protos.AppProtos.HelpInfo value) {
        if (helpInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              helpInfo_ != com.damuzhi.travel.protos.AppProtos.HelpInfo.getDefaultInstance()) {
            helpInfo_ =
              com.damuzhi.travel.protos.AppProtos.HelpInfo.newBuilder(helpInfo_).mergeFrom(value).buildPartial();
          } else {
            helpInfo_ = value;
          }
          onChanged();
        } else {
          helpInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder clearHelpInfo() {
        if (helpInfoBuilder_ == null) {
          helpInfo_ = com.damuzhi.travel.protos.AppProtos.HelpInfo.getDefaultInstance();
          onChanged();
        } else {
          helpInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      public com.damuzhi.travel.protos.AppProtos.HelpInfo.Builder getHelpInfoBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getHelpInfoFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.AppProtos.HelpInfoOrBuilder getHelpInfoOrBuilder() {
        if (helpInfoBuilder_ != null) {
          return helpInfoBuilder_.getMessageOrBuilder();
        } else {
          return helpInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.AppProtos.HelpInfo, com.damuzhi.travel.protos.AppProtos.HelpInfo.Builder, com.damuzhi.travel.protos.AppProtos.HelpInfoOrBuilder> 
          getHelpInfoFieldBuilder() {
        if (helpInfoBuilder_ == null) {
          helpInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.AppProtos.HelpInfo, com.damuzhi.travel.protos.AppProtos.HelpInfo.Builder, com.damuzhi.travel.protos.AppProtos.HelpInfoOrBuilder>(
                  helpInfo_,
                  getParentForChildren(),
                  isClean());
          helpInfo_ = null;
        }
        return helpInfoBuilder_;
      }
      
      // optional .damuzhi.PlaceList placeList = 7;
      private com.damuzhi.travel.protos.PlaceListProtos.PlaceList placeList_ = com.damuzhi.travel.protos.PlaceListProtos.PlaceList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.PlaceListProtos.PlaceList, com.damuzhi.travel.protos.PlaceListProtos.PlaceList.Builder, com.damuzhi.travel.protos.PlaceListProtos.PlaceListOrBuilder> placeListBuilder_;
      public boolean hasPlaceList() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public com.damuzhi.travel.protos.PlaceListProtos.PlaceList getPlaceList() {
        if (placeListBuilder_ == null) {
          return placeList_;
        } else {
          return placeListBuilder_.getMessage();
        }
      }
      public Builder setPlaceList(com.damuzhi.travel.protos.PlaceListProtos.PlaceList value) {
        if (placeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          placeList_ = value;
          onChanged();
        } else {
          placeListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setPlaceList(
          com.damuzhi.travel.protos.PlaceListProtos.PlaceList.Builder builderForValue) {
        if (placeListBuilder_ == null) {
          placeList_ = builderForValue.build();
          onChanged();
        } else {
          placeListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergePlaceList(com.damuzhi.travel.protos.PlaceListProtos.PlaceList value) {
        if (placeListBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              placeList_ != com.damuzhi.travel.protos.PlaceListProtos.PlaceList.getDefaultInstance()) {
            placeList_ =
              com.damuzhi.travel.protos.PlaceListProtos.PlaceList.newBuilder(placeList_).mergeFrom(value).buildPartial();
          } else {
            placeList_ = value;
          }
          onChanged();
        } else {
          placeListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearPlaceList() {
        if (placeListBuilder_ == null) {
          placeList_ = com.damuzhi.travel.protos.PlaceListProtos.PlaceList.getDefaultInstance();
          onChanged();
        } else {
          placeListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      public com.damuzhi.travel.protos.PlaceListProtos.PlaceList.Builder getPlaceListBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getPlaceListFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.PlaceListProtos.PlaceListOrBuilder getPlaceListOrBuilder() {
        if (placeListBuilder_ != null) {
          return placeListBuilder_.getMessageOrBuilder();
        } else {
          return placeList_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.PlaceListProtos.PlaceList, com.damuzhi.travel.protos.PlaceListProtos.PlaceList.Builder, com.damuzhi.travel.protos.PlaceListProtos.PlaceListOrBuilder> 
          getPlaceListFieldBuilder() {
        if (placeListBuilder_ == null) {
          placeListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.PlaceListProtos.PlaceList, com.damuzhi.travel.protos.PlaceListProtos.PlaceList.Builder, com.damuzhi.travel.protos.PlaceListProtos.PlaceListOrBuilder>(
                  placeList_,
                  getParentForChildren(),
                  isClean());
          placeList_ = null;
        }
        return placeListBuilder_;
      }
      
      // optional .damuzhi.CityList cityList = 8;
      private com.damuzhi.travel.protos.AppProtos.CityList cityList_ = com.damuzhi.travel.protos.AppProtos.CityList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.AppProtos.CityList, com.damuzhi.travel.protos.AppProtos.CityList.Builder, com.damuzhi.travel.protos.AppProtos.CityListOrBuilder> cityListBuilder_;
      public boolean hasCityList() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.damuzhi.travel.protos.AppProtos.CityList getCityList() {
        if (cityListBuilder_ == null) {
          return cityList_;
        } else {
          return cityListBuilder_.getMessage();
        }
      }
      public Builder setCityList(com.damuzhi.travel.protos.AppProtos.CityList value) {
        if (cityListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cityList_ = value;
          onChanged();
        } else {
          cityListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder setCityList(
          com.damuzhi.travel.protos.AppProtos.CityList.Builder builderForValue) {
        if (cityListBuilder_ == null) {
          cityList_ = builderForValue.build();
          onChanged();
        } else {
          cityListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder mergeCityList(com.damuzhi.travel.protos.AppProtos.CityList value) {
        if (cityListBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              cityList_ != com.damuzhi.travel.protos.AppProtos.CityList.getDefaultInstance()) {
            cityList_ =
              com.damuzhi.travel.protos.AppProtos.CityList.newBuilder(cityList_).mergeFrom(value).buildPartial();
          } else {
            cityList_ = value;
          }
          onChanged();
        } else {
          cityListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder clearCityList() {
        if (cityListBuilder_ == null) {
          cityList_ = com.damuzhi.travel.protos.AppProtos.CityList.getDefaultInstance();
          onChanged();
        } else {
          cityListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      public com.damuzhi.travel.protos.AppProtos.CityList.Builder getCityListBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getCityListFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.AppProtos.CityListOrBuilder getCityListOrBuilder() {
        if (cityListBuilder_ != null) {
          return cityListBuilder_.getMessageOrBuilder();
        } else {
          return cityList_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.AppProtos.CityList, com.damuzhi.travel.protos.AppProtos.CityList.Builder, com.damuzhi.travel.protos.AppProtos.CityListOrBuilder> 
          getCityListFieldBuilder() {
        if (cityListBuilder_ == null) {
          cityListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.AppProtos.CityList, com.damuzhi.travel.protos.AppProtos.CityList.Builder, com.damuzhi.travel.protos.AppProtos.CityListOrBuilder>(
                  cityList_,
                  getParentForChildren(),
                  isClean());
          cityList_ = null;
        }
        return cityListBuilder_;
      }
      
      // optional .damuzhi.App appInfo = 9;
      private com.damuzhi.travel.protos.AppProtos.App appInfo_ = com.damuzhi.travel.protos.AppProtos.App.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.AppProtos.App, com.damuzhi.travel.protos.AppProtos.App.Builder, com.damuzhi.travel.protos.AppProtos.AppOrBuilder> appInfoBuilder_;
      public boolean hasAppInfo() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public com.damuzhi.travel.protos.AppProtos.App getAppInfo() {
        if (appInfoBuilder_ == null) {
          return appInfo_;
        } else {
          return appInfoBuilder_.getMessage();
        }
      }
      public Builder setAppInfo(com.damuzhi.travel.protos.AppProtos.App value) {
        if (appInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          appInfo_ = value;
          onChanged();
        } else {
          appInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder setAppInfo(
          com.damuzhi.travel.protos.AppProtos.App.Builder builderForValue) {
        if (appInfoBuilder_ == null) {
          appInfo_ = builderForValue.build();
          onChanged();
        } else {
          appInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder mergeAppInfo(com.damuzhi.travel.protos.AppProtos.App value) {
        if (appInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              appInfo_ != com.damuzhi.travel.protos.AppProtos.App.getDefaultInstance()) {
            appInfo_ =
              com.damuzhi.travel.protos.AppProtos.App.newBuilder(appInfo_).mergeFrom(value).buildPartial();
          } else {
            appInfo_ = value;
          }
          onChanged();
        } else {
          appInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder clearAppInfo() {
        if (appInfoBuilder_ == null) {
          appInfo_ = com.damuzhi.travel.protos.AppProtos.App.getDefaultInstance();
          onChanged();
        } else {
          appInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      public com.damuzhi.travel.protos.AppProtos.App.Builder getAppInfoBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getAppInfoFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.AppProtos.AppOrBuilder getAppInfoOrBuilder() {
        if (appInfoBuilder_ != null) {
          return appInfoBuilder_.getMessageOrBuilder();
        } else {
          return appInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.AppProtos.App, com.damuzhi.travel.protos.AppProtos.App.Builder, com.damuzhi.travel.protos.AppProtos.AppOrBuilder> 
          getAppInfoFieldBuilder() {
        if (appInfoBuilder_ == null) {
          appInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.AppProtos.App, com.damuzhi.travel.protos.AppProtos.App.Builder, com.damuzhi.travel.protos.AppProtos.AppOrBuilder>(
                  appInfo_,
                  getParentForChildren(),
                  isClean());
          appInfo_ = null;
        }
        return appInfoBuilder_;
      }
      
      // optional .damuzhi.CommonTravelTipList travelTipList = 10;
      private com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList travelTipList_ = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipListOrBuilder> travelTipListBuilder_;
      public boolean hasTravelTipList() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList getTravelTipList() {
        if (travelTipListBuilder_ == null) {
          return travelTipList_;
        } else {
          return travelTipListBuilder_.getMessage();
        }
      }
      public Builder setTravelTipList(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList value) {
        if (travelTipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          travelTipList_ = value;
          onChanged();
        } else {
          travelTipListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder setTravelTipList(
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.Builder builderForValue) {
        if (travelTipListBuilder_ == null) {
          travelTipList_ = builderForValue.build();
          onChanged();
        } else {
          travelTipListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder mergeTravelTipList(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList value) {
        if (travelTipListBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              travelTipList_ != com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.getDefaultInstance()) {
            travelTipList_ =
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.newBuilder(travelTipList_).mergeFrom(value).buildPartial();
          } else {
            travelTipList_ = value;
          }
          onChanged();
        } else {
          travelTipListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder clearTravelTipList() {
        if (travelTipListBuilder_ == null) {
          travelTipList_ = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.getDefaultInstance();
          onChanged();
        } else {
          travelTipListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.Builder getTravelTipListBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getTravelTipListFieldBuilder().getBuilder();
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipListOrBuilder getTravelTipListOrBuilder() {
        if (travelTipListBuilder_ != null) {
          return travelTipListBuilder_.getMessageOrBuilder();
        } else {
          return travelTipList_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipListOrBuilder> 
          getTravelTipListFieldBuilder() {
        if (travelTipListBuilder_ == null) {
          travelTipListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipListOrBuilder>(
                  travelTipList_,
                  getParentForChildren(),
                  isClean());
          travelTipList_ = null;
        }
        return travelTipListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:damuzhi.TravelResponse)
    }
    
    static {
      defaultInstance = new TravelResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:damuzhi.TravelResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_damuzhi_Package_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_damuzhi_Package_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_damuzhi_TravelResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_damuzhi_TravelResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPackage.proto\022\007damuzhi\032\013Place.proto\032\022C" +
      "ityOverview.proto\032\020TravelTips.proto\032\tApp" +
      ".proto\"n\n\007Package\022\017\n\007version\030\001 \002(\t\022\016\n\006ci" +
      "tyId\030\002 \002(\005\022\020\n\010cityName\030\003 \002(\t\0220\n\010language" +
      "\030\004 \002(\0162\025.damuzhi.LanguageType:\007ZH_HANS\"\367" +
      "\002\n\016TravelResponse\022\025\n\nresultCode\030\001 \002(\005:\0010" +
      "\022\022\n\nresultInfo\030\002 \001(\t\022\035\n\005place\030\003 \001(\0132\016.da" +
      "muzhi.Place\022)\n\010overview\030\004 \001(\0132\027.damuzhi." +
      "CommonOverview\022+\n\ttravelTip\030\005 \001(\0132\030.damu" +
      "zhi.CommonTravelTip\022#\n\010helpInfo\030\006 \001(\0132\021.",
      "damuzhi.HelpInfo\022%\n\tplaceList\030\007 \001(\0132\022.da" +
      "muzhi.PlaceList\022#\n\010cityList\030\010 \001(\0132\021.damu" +
      "zhi.CityList\022\035\n\007appInfo\030\t \001(\0132\014.damuzhi." +
      "App\0223\n\rtravelTipList\030\n \001(\0132\034.damuzhi.Com" +
      "monTravelTipList*0\n\014LanguageType\022\013\n\007ZH_H" +
      "ANS\020\001\022\013\n\007ZH_HANT\020\002\022\006\n\002EN\020\003B$\n\023com.lk.dam" +
      "uzhi.utilB\rPackageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_damuzhi_Package_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_damuzhi_Package_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_damuzhi_Package_descriptor,
              new java.lang.String[] { "Version", "CityId", "CityName", "Language", },
              com.damuzhi.travel.protos.PackageProtos.Package.class,
              com.damuzhi.travel.protos.PackageProtos.Package.Builder.class);
          internal_static_damuzhi_TravelResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_damuzhi_TravelResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_damuzhi_TravelResponse_descriptor,
              new java.lang.String[] { "ResultCode", "ResultInfo", "Place", "Overview", "TravelTip", "HelpInfo", "PlaceList", "CityList", "AppInfo", "TravelTipList", },
              com.damuzhi.travel.protos.PackageProtos.TravelResponse.class,
              com.damuzhi.travel.protos.PackageProtos.TravelResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.damuzhi.travel.protos.PlaceListProtos.getDescriptor(),
          com.damuzhi.travel.protos.CityOverviewProtos.getDescriptor(),
          com.damuzhi.travel.protos.TravelTipsProtos.getDescriptor(),
          com.damuzhi.travel.protos.AppProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
