// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelTips.proto

package com.damuzhi.travel.protos;

public final class TravelTipsProtos {
  private TravelTipsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum TravelTipType
      implements com.google.protobuf.ProtocolMessageEnum {
    GUIDE(0, 1),
    ROUTE(1, 2),
    ;
    
    public static final int GUIDE_VALUE = 1;
    public static final int ROUTE_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static TravelTipType valueOf(int value) {
      switch (value) {
        case 1: return GUIDE;
        case 2: return ROUTE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<TravelTipType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TravelTipType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TravelTipType>() {
            public TravelTipType findValueByNumber(int number) {
              return TravelTipType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.TravelTipsProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final TravelTipType[] VALUES = {
      GUIDE, ROUTE, 
    };
    
    public static TravelTipType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private TravelTipType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:damuzhi.TravelTipType)
  }
  
  public interface CommonTravelTipOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 tipId = 1;
    boolean hasTipId();
    int getTipId();
    
    // optional int32 cityId = 2;
    boolean hasCityId();
    int getCityId();
    
    // required string name = 3;
    boolean hasName();
    String getName();
    
    // optional string html = 4;
    boolean hasHtml();
    String getHtml();
    
    // optional string briefIntro = 5;
    boolean hasBriefIntro();
    String getBriefIntro();
    
    // optional string icon = 6;
    boolean hasIcon();
    String getIcon();
    
    // repeated string images = 7;
    java.util.List<String> getImagesList();
    int getImagesCount();
    String getImages(int index);
    
    // optional string detailIntro = 8;
    boolean hasDetailIntro();
    String getDetailIntro();
  }
  public static final class CommonTravelTip extends
      com.google.protobuf.GeneratedMessage
      implements CommonTravelTipOrBuilder {
    // Use CommonTravelTip.newBuilder() to construct.
    private CommonTravelTip(Builder builder) {
      super(builder);
    }
    private CommonTravelTip(boolean noInit) {}
    
    private static final CommonTravelTip defaultInstance;
    public static CommonTravelTip getDefaultInstance() {
      return defaultInstance;
    }
    
    public CommonTravelTip getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_CommonTravelTip_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_CommonTravelTip_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 tipId = 1;
    public static final int TIPID_FIELD_NUMBER = 1;
    private int tipId_;
    public boolean hasTipId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTipId() {
      return tipId_;
    }
    
    // optional int32 cityId = 2;
    public static final int CITYID_FIELD_NUMBER = 2;
    private int cityId_;
    public boolean hasCityId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCityId() {
      return cityId_;
    }
    
    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string html = 4;
    public static final int HTML_FIELD_NUMBER = 4;
    private java.lang.Object html_;
    public boolean hasHtml() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getHtml() {
      java.lang.Object ref = html_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          html_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHtmlBytes() {
      java.lang.Object ref = html_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        html_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string briefIntro = 5;
    public static final int BRIEFINTRO_FIELD_NUMBER = 5;
    private java.lang.Object briefIntro_;
    public boolean hasBriefIntro() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getBriefIntro() {
      java.lang.Object ref = briefIntro_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          briefIntro_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBriefIntroBytes() {
      java.lang.Object ref = briefIntro_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        briefIntro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string icon = 6;
    public static final int ICON_FIELD_NUMBER = 6;
    private java.lang.Object icon_;
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getIcon() {
      java.lang.Object ref = icon_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          icon_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIconBytes() {
      java.lang.Object ref = icon_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        icon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string images = 7;
    public static final int IMAGES_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList images_;
    public java.util.List<String>
        getImagesList() {
      return images_;
    }
    public int getImagesCount() {
      return images_.size();
    }
    public String getImages(int index) {
      return images_.get(index);
    }
    
    // optional string detailIntro = 8;
    public static final int DETAILINTRO_FIELD_NUMBER = 8;
    private java.lang.Object detailIntro_;
    public boolean hasDetailIntro() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getDetailIntro() {
      java.lang.Object ref = detailIntro_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          detailIntro_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDetailIntroBytes() {
      java.lang.Object ref = detailIntro_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        detailIntro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      tipId_ = 0;
      cityId_ = 0;
      name_ = "";
      html_ = "";
      briefIntro_ = "";
      icon_ = "";
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      detailIntro_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, tipId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cityId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getHtmlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getBriefIntroBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getIconBytes());
      }
      for (int i = 0; i < images_.size(); i++) {
        output.writeBytes(7, images_.getByteString(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getDetailIntroBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tipId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cityId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getHtmlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBriefIntroBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getIconBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < images_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(images_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getImagesList().size();
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDetailIntroBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_CommonTravelTip_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_CommonTravelTip_fieldAccessorTable;
      }
      
      // Construct using com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        tipId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cityId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        html_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        briefIntro_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        icon_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        detailIntro_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDescriptor();
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getDefaultInstanceForType() {
        return com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance();
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip build() {
        com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip buildPartial() {
        com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip result = new com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tipId_ = tipId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cityId_ = cityId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.html_ = html_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.briefIntro_ = briefIntro_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.icon_ = icon_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          images_ = new com.google.protobuf.UnmodifiableLazyStringList(
              images_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.images_ = images_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.detailIntro_ = detailIntro_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip) {
          return mergeFrom((com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip other) {
        if (other == com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance()) return this;
        if (other.hasTipId()) {
          setTipId(other.getTipId());
        }
        if (other.hasCityId()) {
          setCityId(other.getCityId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasHtml()) {
          setHtml(other.getHtml());
        }
        if (other.hasBriefIntro()) {
          setBriefIntro(other.getBriefIntro());
        }
        if (other.hasIcon()) {
          setIcon(other.getIcon());
        }
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
        if (other.hasDetailIntro()) {
          setDetailIntro(other.getDetailIntro());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tipId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cityId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              html_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              briefIntro_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              icon_ = input.readBytes();
              break;
            }
            case 58: {
              ensureImagesIsMutable();
              images_.add(input.readBytes());
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              detailIntro_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 tipId = 1;
      private int tipId_ ;
      public boolean hasTipId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTipId() {
        return tipId_;
      }
      public Builder setTipId(int value) {
        bitField0_ |= 0x00000001;
        tipId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTipId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tipId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 cityId = 2;
      private int cityId_ ;
      public boolean hasCityId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCityId() {
        return cityId_;
      }
      public Builder setCityId(int value) {
        bitField0_ |= 0x00000002;
        cityId_ = value;
        onChanged();
        return this;
      }
      public Builder clearCityId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cityId_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // optional string html = 4;
      private java.lang.Object html_ = "";
      public boolean hasHtml() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getHtml() {
        java.lang.Object ref = html_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          html_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHtml(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        html_ = value;
        onChanged();
        return this;
      }
      public Builder clearHtml() {
        bitField0_ = (bitField0_ & ~0x00000008);
        html_ = getDefaultInstance().getHtml();
        onChanged();
        return this;
      }
      void setHtml(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        html_ = value;
        onChanged();
      }
      
      // optional string briefIntro = 5;
      private java.lang.Object briefIntro_ = "";
      public boolean hasBriefIntro() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getBriefIntro() {
        java.lang.Object ref = briefIntro_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          briefIntro_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBriefIntro(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        briefIntro_ = value;
        onChanged();
        return this;
      }
      public Builder clearBriefIntro() {
        bitField0_ = (bitField0_ & ~0x00000010);
        briefIntro_ = getDefaultInstance().getBriefIntro();
        onChanged();
        return this;
      }
      void setBriefIntro(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        briefIntro_ = value;
        onChanged();
      }
      
      // optional string icon = 6;
      private java.lang.Object icon_ = "";
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getIcon() {
        java.lang.Object ref = icon_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          icon_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIcon(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        icon_ = value;
        onChanged();
        return this;
      }
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000020);
        icon_ = getDefaultInstance().getIcon();
        onChanged();
        return this;
      }
      void setIcon(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        icon_ = value;
        onChanged();
      }
      
      // repeated string images = 7;
      private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          images_ = new com.google.protobuf.LazyStringArrayList(images_);
          bitField0_ |= 0x00000040;
         }
      }
      public java.util.List<String>
          getImagesList() {
        return java.util.Collections.unmodifiableList(images_);
      }
      public int getImagesCount() {
        return images_.size();
      }
      public String getImages(int index) {
        return images_.get(index);
      }
      public Builder setImages(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addImages(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllImages(
          java.lang.Iterable<String> values) {
        ensureImagesIsMutable();
        super.addAll(values, images_);
        onChanged();
        return this;
      }
      public Builder clearImages() {
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      void addImages(com.google.protobuf.ByteString value) {
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
      }
      
      // optional string detailIntro = 8;
      private java.lang.Object detailIntro_ = "";
      public boolean hasDetailIntro() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getDetailIntro() {
        java.lang.Object ref = detailIntro_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          detailIntro_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDetailIntro(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        detailIntro_ = value;
        onChanged();
        return this;
      }
      public Builder clearDetailIntro() {
        bitField0_ = (bitField0_ & ~0x00000080);
        detailIntro_ = getDefaultInstance().getDetailIntro();
        onChanged();
        return this;
      }
      void setDetailIntro(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        detailIntro_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:damuzhi.CommonTravelTip)
    }
    
    static {
      defaultInstance = new CommonTravelTip(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:damuzhi.CommonTravelTip)
  }
  
  public interface CommonTravelTipListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .damuzhi.CommonTravelTip tipList = 1;
    java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> 
        getTipListList();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getTipList(int index);
    int getTipListCount();
    java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
        getTipListOrBuilderList();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getTipListOrBuilder(
        int index);
  }
  public static final class CommonTravelTipList extends
      com.google.protobuf.GeneratedMessage
      implements CommonTravelTipListOrBuilder {
    // Use CommonTravelTipList.newBuilder() to construct.
    private CommonTravelTipList(Builder builder) {
      super(builder);
    }
    private CommonTravelTipList(boolean noInit) {}
    
    private static final CommonTravelTipList defaultInstance;
    public static CommonTravelTipList getDefaultInstance() {
      return defaultInstance;
    }
    
    public CommonTravelTipList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_CommonTravelTipList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_CommonTravelTipList_fieldAccessorTable;
    }
    
    // repeated .damuzhi.CommonTravelTip tipList = 1;
    public static final int TIPLIST_FIELD_NUMBER = 1;
    private java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> tipList_;
    public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> getTipListList() {
      return tipList_;
    }
    public java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
        getTipListOrBuilderList() {
      return tipList_;
    }
    public int getTipListCount() {
      return tipList_.size();
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getTipList(int index) {
      return tipList_.get(index);
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getTipListOrBuilder(
        int index) {
      return tipList_.get(index);
    }
    
    private void initFields() {
      tipList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getTipListCount(); i++) {
        if (!getTipList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < tipList_.size(); i++) {
        output.writeMessage(1, tipList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < tipList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tipList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_CommonTravelTipList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_CommonTravelTipList_fieldAccessorTable;
      }
      
      // Construct using com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTipListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (tipListBuilder_ == null) {
          tipList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tipListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.getDescriptor();
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList getDefaultInstanceForType() {
        return com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.getDefaultInstance();
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList build() {
        com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList buildPartial() {
        com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList result = new com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList(this);
        int from_bitField0_ = bitField0_;
        if (tipListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            tipList_ = java.util.Collections.unmodifiableList(tipList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tipList_ = tipList_;
        } else {
          result.tipList_ = tipListBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList) {
          return mergeFrom((com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList other) {
        if (other == com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.getDefaultInstance()) return this;
        if (tipListBuilder_ == null) {
          if (!other.tipList_.isEmpty()) {
            if (tipList_.isEmpty()) {
              tipList_ = other.tipList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTipListIsMutable();
              tipList_.addAll(other.tipList_);
            }
            onChanged();
          }
        } else {
          if (!other.tipList_.isEmpty()) {
            if (tipListBuilder_.isEmpty()) {
              tipListBuilder_.dispose();
              tipListBuilder_ = null;
              tipList_ = other.tipList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tipListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTipListFieldBuilder() : null;
            } else {
              tipListBuilder_.addAllMessages(other.tipList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getTipListCount(); i++) {
          if (!getTipList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder subBuilder = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTipList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .damuzhi.CommonTravelTip tipList = 1;
      private java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> tipList_ =
        java.util.Collections.emptyList();
      private void ensureTipListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          tipList_ = new java.util.ArrayList<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip>(tipList_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> tipListBuilder_;
      
      public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> getTipListList() {
        if (tipListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tipList_);
        } else {
          return tipListBuilder_.getMessageList();
        }
      }
      public int getTipListCount() {
        if (tipListBuilder_ == null) {
          return tipList_.size();
        } else {
          return tipListBuilder_.getCount();
        }
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getTipList(int index) {
        if (tipListBuilder_ == null) {
          return tipList_.get(index);
        } else {
          return tipListBuilder_.getMessage(index);
        }
      }
      public Builder setTipList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (tipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTipListIsMutable();
          tipList_.set(index, value);
          onChanged();
        } else {
          tipListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTipList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (tipListBuilder_ == null) {
          ensureTipListIsMutable();
          tipList_.set(index, builderForValue.build());
          onChanged();
        } else {
          tipListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTipList(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (tipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTipListIsMutable();
          tipList_.add(value);
          onChanged();
        } else {
          tipListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTipList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (tipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTipListIsMutable();
          tipList_.add(index, value);
          onChanged();
        } else {
          tipListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTipList(
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (tipListBuilder_ == null) {
          ensureTipListIsMutable();
          tipList_.add(builderForValue.build());
          onChanged();
        } else {
          tipListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTipList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (tipListBuilder_ == null) {
          ensureTipListIsMutable();
          tipList_.add(index, builderForValue.build());
          onChanged();
        } else {
          tipListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTipList(
          java.lang.Iterable<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> values) {
        if (tipListBuilder_ == null) {
          ensureTipListIsMutable();
          super.addAll(values, tipList_);
          onChanged();
        } else {
          tipListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTipList() {
        if (tipListBuilder_ == null) {
          tipList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tipListBuilder_.clear();
        }
        return this;
      }
      public Builder removeTipList(int index) {
        if (tipListBuilder_ == null) {
          ensureTipListIsMutable();
          tipList_.remove(index);
          onChanged();
        } else {
          tipListBuilder_.remove(index);
        }
        return this;
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder getTipListBuilder(
          int index) {
        return getTipListFieldBuilder().getBuilder(index);
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getTipListOrBuilder(
          int index) {
        if (tipListBuilder_ == null) {
          return tipList_.get(index);  } else {
          return tipListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
           getTipListOrBuilderList() {
        if (tipListBuilder_ != null) {
          return tipListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tipList_);
        }
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder addTipListBuilder() {
        return getTipListFieldBuilder().addBuilder(
            com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance());
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder addTipListBuilder(
          int index) {
        return getTipListFieldBuilder().addBuilder(
            index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance());
      }
      public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder> 
           getTipListBuilderList() {
        return getTipListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
          getTipListFieldBuilder() {
        if (tipListBuilder_ == null) {
          tipListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder>(
                  tipList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          tipList_ = null;
        }
        return tipListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:damuzhi.CommonTravelTipList)
    }
    
    static {
      defaultInstance = new CommonTravelTipList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:damuzhi.CommonTravelTipList)
  }
  
  public interface TravelTipsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .damuzhi.CommonTravelTip guideList = 1;
    java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> 
        getGuideListList();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getGuideList(int index);
    int getGuideListCount();
    java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
        getGuideListOrBuilderList();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getGuideListOrBuilder(
        int index);
    
    // repeated .damuzhi.CommonTravelTip routeList = 2;
    java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> 
        getRouteListList();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getRouteList(int index);
    int getRouteListCount();
    java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
        getRouteListOrBuilderList();
    com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getRouteListOrBuilder(
        int index);
    
    // optional int32 cityId = 3;
    boolean hasCityId();
    int getCityId();
  }
  public static final class TravelTips extends
      com.google.protobuf.GeneratedMessage
      implements TravelTipsOrBuilder {
    // Use TravelTips.newBuilder() to construct.
    private TravelTips(Builder builder) {
      super(builder);
    }
    private TravelTips(boolean noInit) {}
    
    private static final TravelTips defaultInstance;
    public static TravelTips getDefaultInstance() {
      return defaultInstance;
    }
    
    public TravelTips getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_TravelTips_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_TravelTips_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .damuzhi.CommonTravelTip guideList = 1;
    public static final int GUIDELIST_FIELD_NUMBER = 1;
    private java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> guideList_;
    public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> getGuideListList() {
      return guideList_;
    }
    public java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
        getGuideListOrBuilderList() {
      return guideList_;
    }
    public int getGuideListCount() {
      return guideList_.size();
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getGuideList(int index) {
      return guideList_.get(index);
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getGuideListOrBuilder(
        int index) {
      return guideList_.get(index);
    }
    
    // repeated .damuzhi.CommonTravelTip routeList = 2;
    public static final int ROUTELIST_FIELD_NUMBER = 2;
    private java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> routeList_;
    public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> getRouteListList() {
      return routeList_;
    }
    public java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
        getRouteListOrBuilderList() {
      return routeList_;
    }
    public int getRouteListCount() {
      return routeList_.size();
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getRouteList(int index) {
      return routeList_.get(index);
    }
    public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getRouteListOrBuilder(
        int index) {
      return routeList_.get(index);
    }
    
    // optional int32 cityId = 3;
    public static final int CITYID_FIELD_NUMBER = 3;
    private int cityId_;
    public boolean hasCityId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCityId() {
      return cityId_;
    }
    
    private void initFields() {
      guideList_ = java.util.Collections.emptyList();
      routeList_ = java.util.Collections.emptyList();
      cityId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getGuideListCount(); i++) {
        if (!getGuideList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getRouteListCount(); i++) {
        if (!getRouteList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < guideList_.size(); i++) {
        output.writeMessage(1, guideList_.get(i));
      }
      for (int i = 0; i < routeList_.size(); i++) {
        output.writeMessage(2, routeList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(3, cityId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < guideList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, guideList_.get(i));
      }
      for (int i = 0; i < routeList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, routeList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cityId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.damuzhi.travel.protos.TravelTipsProtos.TravelTips parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.damuzhi.travel.protos.TravelTipsProtos.TravelTips prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.damuzhi.travel.protos.TravelTipsProtos.TravelTipsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_TravelTips_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.damuzhi.travel.protos.TravelTipsProtos.internal_static_damuzhi_TravelTips_fieldAccessorTable;
      }
      
      // Construct using com.damuzhi.travel.protos.TravelTipsProtos.TravelTips.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGuideListFieldBuilder();
          getRouteListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (guideListBuilder_ == null) {
          guideList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          guideListBuilder_.clear();
        }
        if (routeListBuilder_ == null) {
          routeList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          routeListBuilder_.clear();
        }
        cityId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.damuzhi.travel.protos.TravelTipsProtos.TravelTips.getDescriptor();
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.TravelTips getDefaultInstanceForType() {
        return com.damuzhi.travel.protos.TravelTipsProtos.TravelTips.getDefaultInstance();
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.TravelTips build() {
        com.damuzhi.travel.protos.TravelTipsProtos.TravelTips result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.damuzhi.travel.protos.TravelTipsProtos.TravelTips buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.damuzhi.travel.protos.TravelTipsProtos.TravelTips result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.damuzhi.travel.protos.TravelTipsProtos.TravelTips buildPartial() {
        com.damuzhi.travel.protos.TravelTipsProtos.TravelTips result = new com.damuzhi.travel.protos.TravelTipsProtos.TravelTips(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (guideListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            guideList_ = java.util.Collections.unmodifiableList(guideList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.guideList_ = guideList_;
        } else {
          result.guideList_ = guideListBuilder_.build();
        }
        if (routeListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            routeList_ = java.util.Collections.unmodifiableList(routeList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.routeList_ = routeList_;
        } else {
          result.routeList_ = routeListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cityId_ = cityId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.damuzhi.travel.protos.TravelTipsProtos.TravelTips) {
          return mergeFrom((com.damuzhi.travel.protos.TravelTipsProtos.TravelTips)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.damuzhi.travel.protos.TravelTipsProtos.TravelTips other) {
        if (other == com.damuzhi.travel.protos.TravelTipsProtos.TravelTips.getDefaultInstance()) return this;
        if (guideListBuilder_ == null) {
          if (!other.guideList_.isEmpty()) {
            if (guideList_.isEmpty()) {
              guideList_ = other.guideList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGuideListIsMutable();
              guideList_.addAll(other.guideList_);
            }
            onChanged();
          }
        } else {
          if (!other.guideList_.isEmpty()) {
            if (guideListBuilder_.isEmpty()) {
              guideListBuilder_.dispose();
              guideListBuilder_ = null;
              guideList_ = other.guideList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              guideListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGuideListFieldBuilder() : null;
            } else {
              guideListBuilder_.addAllMessages(other.guideList_);
            }
          }
        }
        if (routeListBuilder_ == null) {
          if (!other.routeList_.isEmpty()) {
            if (routeList_.isEmpty()) {
              routeList_ = other.routeList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRouteListIsMutable();
              routeList_.addAll(other.routeList_);
            }
            onChanged();
          }
        } else {
          if (!other.routeList_.isEmpty()) {
            if (routeListBuilder_.isEmpty()) {
              routeListBuilder_.dispose();
              routeListBuilder_ = null;
              routeList_ = other.routeList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              routeListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRouteListFieldBuilder() : null;
            } else {
              routeListBuilder_.addAllMessages(other.routeList_);
            }
          }
        }
        if (other.hasCityId()) {
          setCityId(other.getCityId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getGuideListCount(); i++) {
          if (!getGuideList(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getRouteListCount(); i++) {
          if (!getRouteList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder subBuilder = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGuideList(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder subBuilder = com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRouteList(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cityId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .damuzhi.CommonTravelTip guideList = 1;
      private java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> guideList_ =
        java.util.Collections.emptyList();
      private void ensureGuideListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          guideList_ = new java.util.ArrayList<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip>(guideList_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> guideListBuilder_;
      
      public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> getGuideListList() {
        if (guideListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(guideList_);
        } else {
          return guideListBuilder_.getMessageList();
        }
      }
      public int getGuideListCount() {
        if (guideListBuilder_ == null) {
          return guideList_.size();
        } else {
          return guideListBuilder_.getCount();
        }
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getGuideList(int index) {
        if (guideListBuilder_ == null) {
          return guideList_.get(index);
        } else {
          return guideListBuilder_.getMessage(index);
        }
      }
      public Builder setGuideList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (guideListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuideListIsMutable();
          guideList_.set(index, value);
          onChanged();
        } else {
          guideListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGuideList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (guideListBuilder_ == null) {
          ensureGuideListIsMutable();
          guideList_.set(index, builderForValue.build());
          onChanged();
        } else {
          guideListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGuideList(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (guideListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuideListIsMutable();
          guideList_.add(value);
          onChanged();
        } else {
          guideListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGuideList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (guideListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuideListIsMutable();
          guideList_.add(index, value);
          onChanged();
        } else {
          guideListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGuideList(
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (guideListBuilder_ == null) {
          ensureGuideListIsMutable();
          guideList_.add(builderForValue.build());
          onChanged();
        } else {
          guideListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGuideList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (guideListBuilder_ == null) {
          ensureGuideListIsMutable();
          guideList_.add(index, builderForValue.build());
          onChanged();
        } else {
          guideListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGuideList(
          java.lang.Iterable<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> values) {
        if (guideListBuilder_ == null) {
          ensureGuideListIsMutable();
          super.addAll(values, guideList_);
          onChanged();
        } else {
          guideListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGuideList() {
        if (guideListBuilder_ == null) {
          guideList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          guideListBuilder_.clear();
        }
        return this;
      }
      public Builder removeGuideList(int index) {
        if (guideListBuilder_ == null) {
          ensureGuideListIsMutable();
          guideList_.remove(index);
          onChanged();
        } else {
          guideListBuilder_.remove(index);
        }
        return this;
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder getGuideListBuilder(
          int index) {
        return getGuideListFieldBuilder().getBuilder(index);
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getGuideListOrBuilder(
          int index) {
        if (guideListBuilder_ == null) {
          return guideList_.get(index);  } else {
          return guideListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
           getGuideListOrBuilderList() {
        if (guideListBuilder_ != null) {
          return guideListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(guideList_);
        }
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder addGuideListBuilder() {
        return getGuideListFieldBuilder().addBuilder(
            com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance());
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder addGuideListBuilder(
          int index) {
        return getGuideListFieldBuilder().addBuilder(
            index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance());
      }
      public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder> 
           getGuideListBuilderList() {
        return getGuideListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
          getGuideListFieldBuilder() {
        if (guideListBuilder_ == null) {
          guideListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder>(
                  guideList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          guideList_ = null;
        }
        return guideListBuilder_;
      }
      
      // repeated .damuzhi.CommonTravelTip routeList = 2;
      private java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> routeList_ =
        java.util.Collections.emptyList();
      private void ensureRouteListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          routeList_ = new java.util.ArrayList<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip>(routeList_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> routeListBuilder_;
      
      public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> getRouteListList() {
        if (routeListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routeList_);
        } else {
          return routeListBuilder_.getMessageList();
        }
      }
      public int getRouteListCount() {
        if (routeListBuilder_ == null) {
          return routeList_.size();
        } else {
          return routeListBuilder_.getCount();
        }
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip getRouteList(int index) {
        if (routeListBuilder_ == null) {
          return routeList_.get(index);
        } else {
          return routeListBuilder_.getMessage(index);
        }
      }
      public Builder setRouteList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (routeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouteListIsMutable();
          routeList_.set(index, value);
          onChanged();
        } else {
          routeListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRouteList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (routeListBuilder_ == null) {
          ensureRouteListIsMutable();
          routeList_.set(index, builderForValue.build());
          onChanged();
        } else {
          routeListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRouteList(com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (routeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouteListIsMutable();
          routeList_.add(value);
          onChanged();
        } else {
          routeListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRouteList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip value) {
        if (routeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouteListIsMutable();
          routeList_.add(index, value);
          onChanged();
        } else {
          routeListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRouteList(
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (routeListBuilder_ == null) {
          ensureRouteListIsMutable();
          routeList_.add(builderForValue.build());
          onChanged();
        } else {
          routeListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRouteList(
          int index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder builderForValue) {
        if (routeListBuilder_ == null) {
          ensureRouteListIsMutable();
          routeList_.add(index, builderForValue.build());
          onChanged();
        } else {
          routeListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRouteList(
          java.lang.Iterable<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip> values) {
        if (routeListBuilder_ == null) {
          ensureRouteListIsMutable();
          super.addAll(values, routeList_);
          onChanged();
        } else {
          routeListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRouteList() {
        if (routeListBuilder_ == null) {
          routeList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          routeListBuilder_.clear();
        }
        return this;
      }
      public Builder removeRouteList(int index) {
        if (routeListBuilder_ == null) {
          ensureRouteListIsMutable();
          routeList_.remove(index);
          onChanged();
        } else {
          routeListBuilder_.remove(index);
        }
        return this;
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder getRouteListBuilder(
          int index) {
        return getRouteListFieldBuilder().getBuilder(index);
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder getRouteListOrBuilder(
          int index) {
        if (routeListBuilder_ == null) {
          return routeList_.get(index);  } else {
          return routeListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
           getRouteListOrBuilderList() {
        if (routeListBuilder_ != null) {
          return routeListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routeList_);
        }
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder addRouteListBuilder() {
        return getRouteListFieldBuilder().addBuilder(
            com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance());
      }
      public com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder addRouteListBuilder(
          int index) {
        return getRouteListFieldBuilder().addBuilder(
            index, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.getDefaultInstance());
      }
      public java.util.List<com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder> 
           getRouteListBuilderList() {
        return getRouteListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder> 
          getRouteListFieldBuilder() {
        if (routeListBuilder_ == null) {
          routeListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder, com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipOrBuilder>(
                  routeList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          routeList_ = null;
        }
        return routeListBuilder_;
      }
      
      // optional int32 cityId = 3;
      private int cityId_ ;
      public boolean hasCityId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getCityId() {
        return cityId_;
      }
      public Builder setCityId(int value) {
        bitField0_ |= 0x00000004;
        cityId_ = value;
        onChanged();
        return this;
      }
      public Builder clearCityId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cityId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:damuzhi.TravelTips)
    }
    
    static {
      defaultInstance = new TravelTips(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:damuzhi.TravelTips)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_damuzhi_CommonTravelTip_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_damuzhi_CommonTravelTip_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_damuzhi_CommonTravelTipList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_damuzhi_CommonTravelTipList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_damuzhi_TravelTips_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_damuzhi_TravelTips_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TravelTips.proto\022\007damuzhi\"\223\001\n\017CommonTr" +
      "avelTip\022\r\n\005tipId\030\001 \001(\005\022\016\n\006cityId\030\002 \001(\005\022\014" +
      "\n\004name\030\003 \002(\t\022\014\n\004html\030\004 \001(\t\022\022\n\nbriefIntro" +
      "\030\005 \001(\t\022\014\n\004icon\030\006 \001(\t\022\016\n\006images\030\007 \003(\t\022\023\n\013" +
      "detailIntro\030\010 \001(\t\"@\n\023CommonTravelTipList" +
      "\022)\n\007tipList\030\001 \003(\0132\030.damuzhi.CommonTravel" +
      "Tip\"v\n\nTravelTips\022+\n\tguideList\030\001 \003(\0132\030.d" +
      "amuzhi.CommonTravelTip\022+\n\trouteList\030\002 \003(" +
      "\0132\030.damuzhi.CommonTravelTip\022\016\n\006cityId\030\003 " +
      "\001(\005*%\n\rTravelTipType\022\t\n\005GUIDE\020\001\022\t\n\005ROUTE",
      "\020\002B&\n\022com.damuzhi.travel.protosB\020TravelTipsProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_damuzhi_CommonTravelTip_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_damuzhi_CommonTravelTip_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_damuzhi_CommonTravelTip_descriptor,
              new java.lang.String[] { "TipId", "CityId", "Name", "Html", "BriefIntro", "Icon", "Images", "DetailIntro", },
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.class,
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTip.Builder.class);
          internal_static_damuzhi_CommonTravelTipList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_damuzhi_CommonTravelTipList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_damuzhi_CommonTravelTipList_descriptor,
              new java.lang.String[] { "TipList", },
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.class,
              com.damuzhi.travel.protos.TravelTipsProtos.CommonTravelTipList.Builder.class);
          internal_static_damuzhi_TravelTips_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_damuzhi_TravelTips_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_damuzhi_TravelTips_descriptor,
              new java.lang.String[] { "GuideList", "RouteList", "CityId", },
              com.damuzhi.travel.protos.TravelTipsProtos.TravelTips.class,
              com.damuzhi.travel.protos.TravelTipsProtos.TravelTips.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
